---
meta:
  electron: "1.7.10"
apps:
  - name: tCalendar
    url:
      "https://outlook.office365.com/owa/?realm=getty.edu&exsvurl=1&ll-cc=1033&modurl=1&path=/calendar/view/Month"

  - name: tContact
    url:
      "https://outlook.office.com/owa/?realm=getty.edu&exsvurl=1&ll-cc=1033&modurl=2&path=/people"

  - name: tMail
    url: gmail.com

  - name: Keep
    url: keep.google.com

  - name: LinkedIn
    url: linkedin.com

  - name: LiMail
    url: gmail.com

  - name: Gmail
    url: gmail.com

  - name: LiCal
    icon: ./icons/rcal.icns
    url: calendar.google.com

  - name: devdocs
    url: devdocs.io

  - name: GDrive
    url: https://drive.google.com/drive/
