---
meta:
  electron: "1.7.9"
apps:
  - name: bCalendar
    icon: ./icons/bcalendar.icns
    url:
      "https://outlook.office365.com/owa/?realm=getty.edu&exsvurl=1&ll-cc=1033&modurl=1&path=/calendar/view/Month"

  - name: tPeople
    icon: ./icons/tpeople.icns
    url:
      "https://outlook.office.com/owa/?realm=getty.edu&exsvurl=1&ll-cc=1033&modurl=2&path=/people"

  - name: bKeep
    icon: ./icons/bkeep.icns
    url: keep.google.com

  - name: rKeep
    icon: ./icons/rkeep.icns
    url: keep.google.com

  - name: bMail
    icon: ./icons/bmail.icns
    url: gmail.com

  - name: rMail
    icon: ./icons/rmail.icns
    url: gmail.com

  - name: rCal
    icon: ./icons/rcal.icns
    url: calendar.google.com

  - name: devdocs
    icon: ./icons/devdocs.icns
    url: devdocs.io

  - name: GDrive
    icon: ./icons/GDrive.icns
    url: https://drive.google.com/drive/
